kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registryvolumeclaim
  labels:
     app: {{ .Release.Name }}-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
