---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sonatype-nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sonatype-nexus
    spec:
      containers:
        - name: sonatype-nexus3
          image: sonatype/nexus3
          ports:
            - containerPort: 8081
